title: Sarah Jade Pratt
subtitle: Researcher · Designer · Builder
email: sjp23@sfu.ca
description: >- # this means to ignore newlines until "baseurl:"
  (?:[Ss]ara[h]?\s*)+s is a researcher at Simon Fraser University. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sarahjade.ca" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sarahjip
github_username:  sjip1492
linkedin_username:  sarah-jade-pratt
soundcloud_username: leisurenoise
# footer-credit: "This website was built with love."

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
